# @package _global_

defaults:
  - /examples/embodiment
  - override /planner@evaluation.agents.agent_0.planner: llm_planner
  - override /llm@evaluation.agents.agent_0.planner.plan_config.llm: openai_chat
  
habitat:
  dataset:
    data_path: data/datasets/validation_episodes.json.gz

evaluation:
  agents:
    agent_0:
      planner:        
        _target_: 'embodiment.planner.EmbodimentPlanner'
